name: in_app_picture_in_picture
description: A video player for Flutter with Cupertino and Material play controls
publish_to: "none"
version: 0.0.1

environment:
   sdk: ">=2.13.0 <3.0.0"
   flutter: ">=1.22.0"

dependencies:
   cupertino_icons: ^1.0.6
   flutter:
      sdk: flutter
   provider: ^6.1.2
   video_player: ^2.8.5
   wakelock: ^0.6.2

dev_dependencies:
   flutter_test:
      sdk: flutter
   lint: ^2.3.0

flutter:
   uses-material-design: true
